alias JAVA="java"
SUBSTANCE_VERSION=7.1.00

JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.AquaScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.BarbyPinkScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.BottleGreenScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.BrownScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.CharcoalScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.CremeScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DarkVioletScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.EbonyScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.JadeForestScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.LightAquaScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.LimeGreenScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.OliveScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.OrangeScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.PurpleScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.RaspberryScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.SepiaScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.SteelBlueScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.SunGlareScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.SunsetScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.TerracottaScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.UltramarineScheme

JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedSaturatedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedDesaturatedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedInvertedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedNegatedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedHueShiftedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShadedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedTintedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedTonedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShiftedScheme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShiftedBackgroundScheme
