export JAVA_HOME=`/usr/libexec/java_home -v 9`
alias JAVA="java"
SUBSTANCE_VERSION=7.1.01

JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Autumn
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Business
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.BusinessBlackSteel
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.BusinessBlueSteel
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Cerulean
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Creme
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.CremeCoffee
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Dust
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.DustCoffee
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Gemini
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Graphite
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.GraphiteAqua
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.GraphiteChalk
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.GraphiteGlass
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.GraphiteGold
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Magellan
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Mariner
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.MistAqua
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.MistSilver
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Moderate
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Nebula
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.NebulaBrickWall
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.OfficeBlack2007
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.OfficeBlue2007
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.OfficeSilver2007
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Raven
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Sahara
JAVA -cp ./drop/$SUBSTANCE_VERSION/substance-tools-$SUBSTANCE_VERSION.jar:./drop/$SUBSTANCE_VERSION/substance-tst-$SUBSTANCE_VERSION.jar:./lib/forms-1.2.0.jar:./lib/test/*:./lib/build/swingx-all-1.6.4.jar tools.docrobot.RobotMain tools.docrobot.skins.Twilight
