alias JAVA="java"

JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.AquaScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.BarbyPinkScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.BottleGreenScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.BrownScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.CharcoalScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.CremeScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DarkVioletScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.EbonyScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.JadeForestScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.LightAquaScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.LimeGreenScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.OliveScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.OrangeScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.PurpleScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.RaspberryScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.SepiaScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.SteelBlueScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.SunGlareScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.SunsetScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.TerracottaScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.UltramarineScheme

JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedSaturatedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedDesaturatedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedInvertedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedNegatedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedHueShiftedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShadedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedTintedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedTonedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShiftedScheme
JAVA -cp ./drop/substance-tools.jar:./drop/substance.jar:./drop/substance-tst.jar:./lib/forms-1.2.0.jar:./lib/test/fest-swing-1.2.jar:./lib/test/fest-reflect-1.2.jar:./lib/test/fest-util-1.1.2.jar tools.docrobot.RobotMain tools.docrobot.schemes.DerivedShiftedBackgroundScheme
